### ISSUE TITLE
py-R-FCN model

### ISSUE THREAD

**Issue by alashkari** [yanxp/SSM#1]
Hi, 

Are you using this model as the py-R-FCN model?
https://github.com/YuwenXiong/py-R-FCN

If yes, since the authors of py-R-FCN recommend using MXNet version of R-FCN/Deformable R-FCN, have you tested this implementation with the SSM model?

Regards.

**Comment by yanxp** [comment]
Yes, we used the  py-R-FCN model. We didn't tested our SSM model using the MXNet version of R-FCN/Deformable R-FCN. I think it's easy to implement , and you can try it.
