### ISSUE TITLE
Double else in train_net.py

### ISSUE THREAD

**Issue by tommyjiang** [yanxp/SSM#2]
After I clone the source code, I notice one error reported by IDE that there are double elses in `train_net.py`, please refer to https://github.com/yanxp/SSM/blob/master/tools/train_net.py#L232 and https://github.com/yanxp/SSM/blob/master/tools/train_net.py#L239 respectively. Maybe there is something wrong with the source code.

Thank you.

**Comment by yanxp** [comment]
@tommyjiang Thank you for reminding, we have revised the error. You can also see the version of https://github.com/yanxp/SSM-pytorch which is right.

**Comment by tommyjiang** [comment]
Thanks for your work.
