### ISSUE TITLE
Classifier problem: m one-vs-rest or only one classifier

### ISSUE THREAD

**Issue by tommyjiang** [yanxp/SSM#3]
The paper mentions in Section 3.1 that there are **m** classifier by the **one-vs-rest strategy**. But in this implementation only one classifier is used instead of **m one-vs-rest classifers**. 

If so, the example naturally satisfies one of the two conditions in Section 3.2 about the pseudo-labeling, i. e., it is either positive for one class(class score >= 0.5) or negative for all classes(all class scores < 0.5). That means the constraint in Eqn. (7) is naturally satisfied, cause the example is not possible to be positive for more than one class, so we do not need to consider this constraint. Please correct me if I understand in the wrong way. Thank you.

**Comment by yanxp** [comment]
Hello,we consider the m classifiers by the one-vs-rest strategy in the  line https://github.com/yanxp/SSM/blob/master/tools/train_net.py#L211
that if a candidate is positive only one classifier will be satisfied and others will be ignored or negative for all classifiers.
Second , there are maybe some unseen object categories in the unlabeled images, so we need the constraint.

**Comment by tommyjiang** [comment]
Thanks for the reply. 

Yeah I see the code in https://github.com/yanxp/SSM/blob/master/tools/train_net.py#L211. But the train.prototxt in this repo use **one classifier for (K+1) classes** instead of **K classifiers for two classes**. Under this condition, the constraints can be removed. Maybe in your experiment you use **K** independent two-class classifiers?

**Comment by tommyjiang** [comment]
I suppose by using the K+1 class classifier, there are only two cases.

1. The highest score among all classes is larger than 0.5. In this case, the highest score class is treated as the GT.
2. All class scores are under 0.5. In this case, the box does not belong to any class.

Thanks for your reply.
