### ISSUE TITLE
The purpose of `judge_v`

### ISSUE THREAD

**Issue by tommyjiang** [yanxp/SSM#4]
Hi, I notice one function called `judge_v` here https://github.com/yanxp/SSM/blob/8f0aaaf6079d7638e380e2aca4c370b641a50311/lib/utils/help.py#L128 

This function seems to calculate the sum of loss and compare it with one hyper-paremeter(gamma) to decide whether to add this image to the SS process or the AL process. However, I found no description about this procedure. Besides, the `v_val` returned by this function is not used in the following code. So I wonder the purpose of this function. Thank you.

**Comment by yanxp** [comment]
The function aims to calculate sample latent weight V according to our paper Eqn4. to judge whether choose SS process or AL process.

**Comment by tommyjiang** [comment]
I notice that in Eqn (4) `v` has two values: 0 or 1, according to the values of `l` and `f` function. But in this function, there is gamma and `clslambda`, which is not mentioned in the paper. Am I missing something in the paper or could you please explain how `v` is chosen according to Eqn (4)?

**Comment by yanxp** [comment]
The more details you can see our journal "Cost-effective Object Detection: Active Sample
Mining with Switchable Selection Criteria". Thanks

**Comment by tommyjiang** [comment]
Thank you. I will refer to the paper for more details.

**Comment by tommyjiang** [comment]
Hi @yanxp, I have read the paper "Cost-effective Object Detection: Active Sample
Mining with Switchable Selection Criteria". I know that `v` is used to determine which process(AL or SS) the box belongs. But still, the `v_val` returned by this function is not used in the following code. So I suppose only gamma and `v` is useful here.

**Comment by yanxp** [comment]
In our code, the function judge_v() is a selective function to choose AL process or SS process.

**Comment by tommyjiang** [comment]
https://github.com/yanxp/SSM/blob/8f0aaaf6079d7638e380e2aca4c370b641a50311/lib/utils/help.py#L128 

This function returns two values: `v` and `v_val`.

As you mentioned, `v` is used to determine which process (AL or SS) the image enters. But my question is how is `v_val` used? It seems `v_val` is not used after it is returned.

**Comment by tommyjiang** [comment]
No response from the author, closed.
