### ISSUE TITLE
Batch training

### ISSUE THREAD

**Issue by tommyjiang** [yanxp/SSM#5]
Algorithm 1 in the paper refers to batch training, which is for all the mini-batches, update V, H, Y and W. But in this repo, all unlabeled images are chosen to enter AL or SS process and then update the whole roidb and fine tune the network.

So there is some gaps between the paper and the code. Could you share your considerations on this? Thank you.

**Comment by yanxp** [comment]
You can set the amount of unlabeled images to a small number. In this way , we found it faster and  got similar results as our paper.
